### ISSUE TITLE
Could you please provide an example of CamundaPlatform 7 (not zeebe)

### ISSUE THREAD

**Issue by zxiaozhou** [bpmn-io/bpmn-js-connectors-extension#36]
Could you please provide an example of CamundaPlatform

**Comment by MaxTru** [comment]
Thanks for reporting this feedback.

So far, the connectors extension is focussed on Camunda Platform 8 / zeebe diagrams. However, I would like to keep this issue open to collect feedback. 

Still, please update this issue to comply with our [issue templates](https://github.com/bpmn-io/bpmn-js-connectors-extension/issues/new/choose). This way it is easier for us to understand, evaluate, and prioritize issues. Thanks

**Comment by nikku** [comment]
@zxiaozhou As the documentation states this should work just fine with Camunda Platform 7 (with a few limitations where element template support for Camunda Platform 8 is limited):

![image](https://user-images.githubusercontent.com/58601/163384871-fa96b884-1201-410a-b4b8-d8d0c27539fb.png)

I'd ask you to simply adopt the example (replace Zeebe and Camunda Cloud related providers with their Camunda Platform equivalents) and report any issue you find. Thank you!

**Comment by marstamm** [comment]
Closing as we don't plan to add examples right now. Feel free to open issues should you find issues when adopting it for Camunda Platform 7
