### ISSUE TITLE
Only allow selecting latest version of templates

### ISSUE THREAD

**Issue by SebastianStamm** [bpmn-io/bpmn-js-connectors-extension#38]
__Is your feature request related to a problem? Please describe__

When having multiple verions of the same template (different `version` numbers for templates with the same `id`), the "append connector", "change element" and "choose element template" menus list all versions of the template. This can be confusing as the name and description of the connector can stay the same and there is no other indicator (like version number) for users to distinguish between different versions.

__Describe the solution you'd like__

* When choosing a template to assign to an element, only the latest version of a template is available.
* When creating/appending anything only show latest version of templates
* When replacing, only show latest version of templates

__Describe alternatives you've considered__

We could only pass the latest versions of templates into the extension. However, as the extension also influences which templates are available in the properties panel, this is not a good alternative as it would break diagrams which use older versions of the template. Not having older versions available would lead to a "Template not found" message in the properties panel instead of the desired "Update available"

----

Required by https://github.com/camunda/web-modeler/issues/1183.

**Comment by nikku** [comment]
Thanks for opening this issue. We've discussed this earlier already and settled on "only showing latest" from the replace / append / append connector menus.

Something we just need to implement.

**Comment by nikku** [comment]
If you would like to contribute this feature: PR's are welcome on this.

**Comment by nikku** [comment]
Scheduled this for implementation in the next iteration @SebastianStamm @CatalinaMoisuc.

**Comment by nikku** [comment]
@Skaiir Updated with details on where to integrate this. As discussed only latest version of available template shall be available everywhere.

**Comment by nikku** [comment]
Released with v0.4.0.
