### ISSUE TITLE
Append anything removes content of direct editing

### ISSUE THREAD

**Issue by barmac** [bpmn-io/bpmn-js-connectors-extension#40]
__Describe the Bug__

When I click on append anything icon with the direct editing open, it removes the current state.

__Steps to Reproduce__

https://user-images.githubusercontent.com/28307541/171350820-75512b2c-66b0-444b-8e9a-3b69ad8908d3.mov

__Expected Behavior__

Direct editing should save the content of the box.

__Environment__

- Host (Browser/Node version), if applicable: [e.g. MS Edge 18, Chrome 69, Node 10 LTS]
- OS: [e.g. Windows 7]
- Library version: [e.g. 2.0.0]

**Comment by MaxTru** [comment]
Proposing this for `ready`
