### ISSUE TITLE
Example: `Select` action throws error

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/bpmn-js-connectors-extension#43]
__Describe the Bug__

When clicking on the `Select` action inside the properties panel to open the element templates chooser, nothing happens and it throws an error on the current `master`.

> EventBus.js?fdb0:385 unhandled error in event listener TypeError: Cannot read properties of undefined (reading 'id')
>     at _.ChangeMenuResult [as constructor] (ChangeMenuResult.js?96d4:20:16)
>     at _.O [as render] (preact.module.js?da65:1:7979)
>     at j (preact.module.js?da65:1:5671)
>     at w (preact.module.js?da65:1:2130)
>     at j (preact.module.js?da65:1:5834)
>     at w (preact.module.js?da65:1:2130)
>     at L (preact.module.js?da65:1:7176)
>     at j (preact.module.js?da65:1:6107)
>     at w (preact.module.js?da65:1:2130)
>     at L (preact.module.js?da65:1:7176)

__Steps to Reproduce__

1. `npm start`
2. Select element
3. Click on `Select` in the properties panel
4. Nothing happens + console shows an error

__Expected Behavior__

Element template chooser should appear as expected.

__Environment__

- Host (Browser/Node version), if applicable: Chrome 102.0.5005.61
- OS: macOS 11.6.5
- Library version: `master`

**Comment by pinussilvestrus** [comment]
This is related to [the example](https://github.com/bpmn-io/bpmn-js-connectors-extension/tree/master/example) as most example connectors do not provide a `category`. We could either [make the component more forgiving](https://github.com/bpmn-io/bpmn-js-connectors-extension/blob/master/src/common/ChangeMenuResult.js#L20) or [add categories to the example templates](https://github.com/bpmn-io/bpmn-js-connectors-extension/tree/master/example/.camunda/element-templates).

**Comment by nikku** [comment]
Opted for option :two:, making the component more forgiving via https://github.com/bpmn-io/bpmn-js-connectors-extension/pull/44.
